export const FETCH_PROCEDURES_SUCCESS = 'FETCH_PROCEDURES_SUCCESS';
export const FETCH_PROCEDURES_ERROR = 'FETCH_PROCEDURES_ERROR';
export const ADD_PROCEDURE_SUCCESS = 'ADD_PROCEDURE_SUCCESS';
export const ADD_PROCEDURE_ERROR = 'ADD_PROCEDURE_ERROR';

export const FETCH_DOCTORS_SUCCESS = 'FETCH_DOCTORS_SUCCESS';
export const FETCH_DOCTORS_ERROR = 'FETCH_DOCTORS_ERROR';

export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR';

export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_ERROR = 'FETCH_PATIENTS_ERROR';
export const ADD_PATIENT = 'ADD_PATIENT';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_ERROR = 'ADD_PATIENT_ERROR';